const documents = [
	{
		id: 1,
		title: 'Zacatecas, estado de',
		text: 'Estado de',
		slot: '788',
	},
	{
		id: 2,
		title: 'Zacatecas, division politica',
		text: 'Division politica',
		slot: '788',
	},
	{
		id: 3,
		title: 'Zapata Emiliano',
		text: 'Emiliano Zapata (Biografia)',
		slot: '788',
	},
	{
		id: 4,
		title: 'Zaragoza Ignacio',
		text: '(Cromo 4)',
		slot: '788',
	},
	{
		id: 5,
		title: 'Yucatan, estado de',
		text: 'Estado de',
		slot: '787',
	},
	{
		id: 6,
		title: 'Yucatan, division politica',
		text: 'Division politica',
		slot: '787',
	},
	{
		id: 7,
		title: 'Voto, el',
		text: 'Voto, el',
		slot: '971',
	},
	{
		id: 8,
		title: 'Puebla, division politica',
		text: 'Division politica',
		slot: '1302',
	},
	{
		id: 9,
		title: 'Queretaro, division politica',
		text: 'Division politica',
		slot: '778',
	},
	{
		id: 10,
		title: 'Recursos naturales de Mexico',
		text: 'Recursos naturales de Mexico',
		slot: '1118',
	},
	{
		id: 11,
		title: 'Reforestacion',
		text: 'Reforestacion',
		slot: '1118',
	},
	{
		id: 12,
		title: 'Reino vegetal animal',
		text: 'Reino vegetal y animal',
		slot: '1082',
	},
	{
		id: 13,
		title: 'Relieve de la tierra',
		text: 'Llanuras, meseta, cordillera',
		slot: '1082',
	},
	{
		id: 14,
		title: 'Regiones y grupos primitivos',
		text: 'Historia de regiones y grupos primitivos',
		slot: '1082',
	},
	{
		id: 15,
		title: 'Roma su origen y la epoca',
		text: 'Roma su origen y la epoca republicana',
		slot: '572',
	},
	{
		id: 16,
		title: 'Imperio romano',
		text: 'Roma, Imperio romano',
		slot: '572',
	},
	{
		id: 17,
		title: 'Selva tropical',
		text: 'Selva tropical, humeda y seca',
		slot: '1321',
	},
	{
		id: 18,
		title: 'Sinaloa',
		text: 'Estado de Sinaloa',
		slot: '781',
	},
	{
		id: 19,
		title: 'Linfatico',
		text: 'Sistema linfatico',
		slot: '781',
	},
	{
		id: 20,
		title: 'Sol',
		text: 'El sol',
		slot: 'll98',
	},
	{
		id: 21,
		title: 'Sonora',
		text: 'Estado de sonora',
		slot: '782',
	},
	{
		id: 22,
		title: 'Sonora',
		text: 'Division politica',
		slot: '782',
	},
	{
		id: 23,
		title: 'Sor Juana Ines de la Cruz',
		text: 'Sor Juana Ines de la Cruz',
		slot: '782',
	},
	{
		id: 24,
		title: 'Suecia y Finlandia',
		text: 'Suecia y Finlandia',
		slot: '1168',
	},
	{
		id: 25,
		title: 'Tabasco',
		text: 'Tabasco division politica',
		slot: '951',
	},
	{
		id: 26,
		title: 'Tamaulipas',
		text: 'Tamaulipas division politica',
		slot: '675',
	},
	{
		id: 27,
		title: 'Tierra y su contaminacion',
		text: 'Tierra y su contaminacion',
		slot: '1211',
	},
	{
		id: 28,
		title: 'Tlaxcala',
		text: 'Tlaxcala division politica',
		slot: '1211',
	},
	{
		id: 29,
		title: 'Transportes',
		text: 'Transportes aereos, terrestres y maritimos',
		slot: '1121',
	},
	{
		id: 30,
		title: 'Uruguay',
		text: 'Uruguay',
		slot: '740',
	},
	{
		id: 31,
		title: 'Veracruz',
		text: 'Veracruz division politica',
		slot: '740',
	},
	{
		id: 32,
		title: 'Veracruz',
		text: 'Veracruz division politica',
		slot: '740',
	},
	{
		id: 33,
		title: 'Villa Francisco',
		text: 'Francisco Villa(Biografia)',
		slot: '918',
	},
	{
		id: 34,
		title: 'Iturbide Agustin de',
		text: 'Agustin de Iturbide (Biografia)',
		slot: '731',
	},
	{
		id: 35,
		title: 'Jalisco',
		text: 'Jalisco division politica',
		slot: '770',
	},
	{
		id: 36,
		title: 'Juarez Benito',
		text: 'Benito Juarez (Biografia)',
		slot: '770',
	},
	{
		id: 37,
		title: 'Madero Francisco',
		text: 'Francisco I Madero (Biografia)',
		slot: '618',
	},
	{
		id: 38,
		title: 'Mamiferos',
		text: 'Mamiferos (Animales acuaticos)',
		slot: '1379',
	},
	{
		id: 39,
		title: 'Menstruacion',
		text: 'Menstruacion',
		slot: '975',
	},
	{
		id: 40,
		title: 'Metamorfosis',
		text: 'Metamorfosis de la rana',
		slot: '967',
	},
	{
		id: 41,
		title: 'Michoacan',
		text: 'Michoacan Division politica',
		slot: '772',
	},
	{
		id: 42,
		title: 'Morelos',
		text: 'Morelos Division politica',
		slot: '1316',
	},
	{
		id: 43,
		title: 'Morelos',
		text: 'Jose Maria Morelos (Biografia)',
		slot: '1316',
	},
	{
		id: 44,
		title: 'Oaxaca',
		text: 'Oaxaca Division politica',
		slot: '776',
	},
	{
		id: 45,
		title: 'Obesidad, diabetes',
		text: 'Obesidad, diabetes y sus enfermedades',
		slot: '776',
	},
	{
		id: 46,
		title: 'Partidos politicos Mexico',
		text: 'Partidos politicos Mexico',
		slot: '816',
	},
	{
		id: 47,
		title: 'Petroleo',
		text: 'Expropiacion petrolera',
		slot: '1286',
	},
	{
		id: 48,
		title: 'Pintura y su historia',
		text: 'Las bellas artes',
		slot: '720',
	},
	{
		id: 49,
		title: 'Escudo de los estados',
		text: 'Escudo de los estados mexicanos',
		slot: '635',
	},
	{
		id: 50,
		title: 'Las estrellas',
		text: 'Las estrellas',
		slot: '716',
	},
	{
		id: 51,
		title: 'Evolucion de la bandera',
		text: 'Evolucion de la bandera',
		slot: '888',
	},
	{
		id: 52,
		title: 'Factores bioticos y abioticos',
		text: 'Seres vivos y muertos',
		slot: '1010 y 1011',
	},
	{
		id: 52,
		title: 'Fauna de Mexico',
		text: 'Fauna de Mexico',
		slot: '666',
	},
	{
		id: 53,
		title: 'Las frutas',
		text: 'Las frutas',
		slot: '792',
	},
	{
		id: 54,
		title: 'Fundacion de puebla',
		text: 'Fundacion de puebla',
		slot: '1079',
	},
	{
		id: 55,
		title: 'Guanajuato',
		text: 'Guanajuato Division politica',
		slot: '1304',
	},
	{
		id: 56,
		title: 'Guerrero',
		text: 'Guerrero Division politica',
		slot: '1359',
	},
	{
		id: 57,
		title: 'Guerrero',
		text: 'Vicente Guerrero (Biografia)',
		slot: '1359',
	},
	{
		id: 58,
		title: 'Hidalgo y Costilla Miguel',
		text: 'Miguel Hidalgo y Costilla (Biografia)',
		slot: '1318',
	},
	{
		id: 59,
		title: 'Higiene escolar',
		text: 'Dia mundial de la salud e higiene',
		slot: '1247',
	},
	{
		id: 60,
		title: 'Higiene sexual',
		text: 'Higiene sexual',
		slot: '1247',
	},
	{
		id: 61,
		title: 'Himno nacional mexicano',
		text: 'Himno nacional mexicano',
		slot: '536',
	},
	{
		id: 62,
		title: 'Imperio persa y medo',
		text: 'Imperio persa y medo',
		slot: '1038',
	},
	{
		id: 63,
		title: 'Coahuila',
		text: 'Coahuila Division politica',
		slot: '1349',
	},
	{
		id: 64,
		title: 'Conocimiento empirico y cientifico',
		text: 'Conocimiento empirico y cientifico',
		slot: '1331',
	},
	{
		id: 65,
		title: 'Contaminacion',
		text: 'Sus causas y consecuencias',
		slot: '645',
	},
	{
		id: 66,
		title: 'Dia mundial del medio ambiente',
		text: 'Dia mundial del medio ambiente',
		slot: '645',
	},
	{
		id: 67,
		title: 'Contaminacion',
		text: 'La basura organica e inorganica',
		slot: '645',
	},
	{
		id: 68,
		title: 'Cultura teotihuacana',
		text: 'Cultura teotihuacana',
		slot: '505',
	},
	{
		id: 69,
		title: 'Cultura zapoteca',
		text: 'Cultura zapoteca',
		slot: '505',
	},
	{
		id: 70,
		title: 'Dia de muertos',
		text: 'Tradiciones mexicanas',
		slot: '613 o 663',
	},
	{
		id: 71,
		title: 'Diaz Porfirio',
		text: 'Porfirio Diaz (Biografia)',
		slot: '538',
	},
	{
		id: 72,
		title: 'Los dientes',
		text: 'Los dientes',
		slot: '538',
	},
	{
		id: 73,
		title: 'Discriminacion',
		text: 'La discriminacion',
		slot: '1165',
	},
	{
		id: 74,
		title: 'Distrito federal',
		text: 'Division politica',
		slot: '765',
	},
	{
		id: 75,
		title: 'Dulces mexicanos',
		text: 'Dulces mexicanos',
		slot: '1396',
	},
	{
		id: 76,
		title: 'Durango',
		text: 'Durango Division politica',
		slot: '1396',
	},
	{
		id: 77,
		title: 'La educacion',
		text: 'La escuela',
		slot: '576',
	},
	{
		id: 78,
		title: 'Epistola de Melchor Ocampo',
		text: 'Epistola de Melchor Ocampo',
		slot: '1365',
	},
	{
		id: 79,
		title: 'Epoca moderna',
		text: 'Epoca moderna',
		slot: '599',
	},
	{
		id: 80,
		title: 'Eras geologicas',
		text: 'Eras geologicas',
		slot: '599',
	}
]

export default documents

